import type { Issue } from "@deveprobe/shared";
import { IssueSource, IssueMode, IssueStatus, Severity, Priority } from "@deveprobe/shared";

export const MOCK_ISSUES: Issue[] = [
  {
    id: "iss-001",
    orgId: "org-1",
    projectId: "proj-1",
    createdById: "user-1",
    source: IssueSource.EXTENSION,
    mode: IssueMode.SCREEN_RECORDING,
    title: "Checkout flow breaks when applying discount code on mobile",
    summary: "After entering a discount code on iOS Safari, the total price field freezes and the Apply button stops responding. Requires hard reload.",
    status: IssueStatus.OPEN,
    severity: Severity.CRITICAL,
    priority: Priority.URGENT,
    pageUrl: "https://app.example.com/checkout",
    environment: "production",
    browserMeta: { browser: "Safari", os: "iOS 17.4", device: "iPhone 15" },
    assigneeId: null,
    labels: ["checkout", "mobile"],
    duplicateGroupId: null,
    externalLinks: [],
    visibility: "private",
    aiConfidence: 0.91,
    privacyFlags: [],
    publishedAt: null,
    createdAt: new Date("2026-05-03T08:12:00Z"),
    updatedAt: new Date("2026-05-03T08:12:00Z"),
  },
  {
    id: "iss-002",
    orgId: "org-1",
    projectId: "proj-1",
    createdById: "user-2",
    source: IssueSource.EXTENSION,
    mode: IssueMode.LIVE_ANNOTATION,
    title: "Dropdown menu overflows viewport on 1280px breakpoint",
    summary: "The account dropdown in the top nav clips outside the right edge of the screen at exactly 1280px. Visible on Chrome and Firefox.",
    status: IssueStatus.TRIAGED,
    severity: Severity.MEDIUM,
    priority: Priority.MEDIUM,
    pageUrl: "https://app.example.com/dashboard",
    environment: "staging",
    browserMeta: { browser: "Chrome", os: "macOS 14", viewport: "1280x800" },
    assigneeId: "user-3",
    labels: ["ui", "responsive"],
    duplicateGroupId: null,
    externalLinks: [{ provider: "linear", externalId: "ENG-204", url: "https://linear.app/t/ENG-204", syncedAt: new Date() }],
    visibility: "private",
    aiConfidence: 0.85,
    privacyFlags: [],
    publishedAt: null,
    createdAt: new Date("2026-05-03T07:45:00Z"),
    updatedAt: new Date("2026-05-03T09:01:00Z"),
  },
  {
    id: "iss-003",
    orgId: "org-1",
    projectId: "proj-2",
    createdById: "user-1",
    source: IssueSource.EXTENSION,
    mode: IssueMode.SCREENSHOT,
    title: "404 on direct navigation to /reports/:id",
    summary: "Navigating directly to a report URL returns a 404 from the server. Works fine via in-app router links. Likely missing SSR catch-all route.",
    status: IssueStatus.IN_PROGRESS,
    severity: Severity.HIGH,
    priority: Priority.HIGH,
    pageUrl: "https://app.example.com/reports/rpt-4812",
    environment: "production",
    browserMeta: { browser: "Chrome", os: "Windows 11" },
    assigneeId: "user-1",
    labels: ["routing", "ssr"],
    duplicateGroupId: null,
    externalLinks: [],
    visibility: "private",
    aiConfidence: 0.78,
    privacyFlags: [],
    publishedAt: null,
    createdAt: new Date("2026-05-02T16:30:00Z"),
    updatedAt: new Date("2026-05-03T09:20:00Z"),
  },
  {
    id: "iss-004",
    orgId: "org-1",
    projectId: "proj-1",
    createdById: "user-3",
    source: IssueSource.EXTENSION,
    mode: IssueMode.SCREEN_RECORDING,
    title: "Auth token not refreshed after 24h session expiry",
    summary: "Silent token refresh fails silently after the 24-hour window. User gets logged out mid-session with no error message.",
    status: IssueStatus.AWAITING_VERIFICATION,
    severity: Severity.HIGH,
    priority: Priority.HIGH,
    pageUrl: "https://app.example.com/",
    environment: "production",
    browserMeta: { browser: "Firefox", os: "Ubuntu 22.04" },
    assigneeId: "user-1",
    labels: ["auth", "session"],
    duplicateGroupId: null,
    externalLinks: [{ provider: "github", externalId: "421", url: "https://github.com/acme/app/issues/421", syncedAt: new Date() }],
    visibility: "private",
    aiConfidence: 0.95,
    privacyFlags: [],
    publishedAt: null,
    createdAt: new Date("2026-05-01T11:00:00Z"),
    updatedAt: new Date("2026-05-03T10:05:00Z"),
  },
  {
    id: "iss-005",
    orgId: "org-1",
    projectId: "proj-2",
    createdById: "user-2",
    source: IssueSource.EXTENSION,
    mode: IssueMode.LIVE_ANNOTATION,
    title: "Copy typo on onboarding step 3 — 'recieve' should be 'receive'",
    summary: null,
    status: IssueStatus.RESOLVED,
    severity: Severity.LOW,
    priority: Priority.LOW,
    pageUrl: "https://app.example.com/onboarding/step/3",
    environment: "staging",
    browserMeta: { browser: "Chrome", os: "macOS 14" },
    assigneeId: "user-2",
    labels: ["copy"],
    duplicateGroupId: null,
    externalLinks: [],
    visibility: "private",
    aiConfidence: null,
    privacyFlags: [],
    publishedAt: null,
    createdAt: new Date("2026-04-30T14:22:00Z"),
    updatedAt: new Date("2026-05-02T09:10:00Z"),
  },
  {
    id: "iss-006",
    orgId: "org-1",
    projectId: "proj-1",
    createdById: "user-1",
    source: IssueSource.EXTENSION,
    mode: IssueMode.SCREEN_RECORDING,
    title: "Network request to /api/v2/billing hangs indefinitely on slow 3G",
    summary: "No timeout is set on the billing fetch. On simulated slow 3G, the request hangs forever with no loading state or error shown.",
    status: IssueStatus.OPEN,
    severity: Severity.HIGH,
    priority: Priority.MEDIUM,
    pageUrl: "https://app.example.com/settings/billing",
    environment: "production",
    browserMeta: { browser: "Chrome", os: "macOS 14" },
    assigneeId: null,
    labels: ["network", "billing", "performance"],
    duplicateGroupId: null,
    externalLinks: [],
    visibility: "private",
    aiConfidence: 0.82,
    privacyFlags: [],
    publishedAt: null,
    createdAt: new Date("2026-05-03T09:55:00Z"),
    updatedAt: new Date("2026-05-03T09:55:00Z"),
  },
];

export const MOCK_PROJECTS = [
  { id: "proj-1", name: "Web App", slug: "web-app" },
  { id: "proj-2", name: "Marketing Site", slug: "marketing-site" },
];
